import {IsNullOrEmpty} from './validation.helper.js';

export const cloneArray = arr => arr.map(x => x);
export const removeEmptyValues = arr => arr.filter(v => !IsNullOrEmpty(v));
export const getUntilIndex = (input, index) => Array.isArray(input) ? input.slice(0, index + 1) : Object.fromEntries(Object.entries(input).slice(0, index + 1));
export const pluck = (arr, key) => arr.map(obj => obj[key]);
export const ArrfindStrict = (Arr, search) =>Arr.find(element => element === search);
export const Arrfind = (Arr, search) => Arr.find(element => element == search);
export const filterByKey = (arr, key, value) => arr.filter(obj => obj[key] == value);
export const findByKey = (arr, key, value) => arr.find(obj => obj[key] == value);
export const intersection = (arr, values) => (values = new Set(values),arr.filter(v => values.has(v)));
export const intersectionByKey = (arr, values, key) => (values = new Set(values.map(v => v[key])),arr.filter(v => values.has(v[key])));
export const differenceByKey = (arr, values, key) => (values = new Set(values.map(v => v[key])),arr.filter(v => !values.has(v[key])));
export const sortBy = (arr, key, order = "asc") => arr.sort((a, b) => (order === "asc" ? 1 : -1) * ((a[key] > b[key]) - (a[key] < b[key])));
export const unique = arr => [...new Set(arr)];
export const uniqueBy = (arr, key) => [...new Map(arr.map(x => [x[key], x])).values()];
export const groupBy = (arr, key) => arr.reduce((a,v)=>((a[v[key]]??=[]).push(v),a),{});
export const countBy = (arr, key) => arr.reduce((a,v)=>(a[v[key]]=(a[v[key]]||0)+1,a),{});
export const indexBy = (arr, key) => Object.fromEntries(arr.map(x=>[x[key],x]));
export const partition = (arr, fn) => arr.reduce(([a,b],v)=>(fn(v)?a:b).push(v),[[],[]]);
export const chunk = (arr,size) => Array.from({length:Math.ceil(arr.length/size)},(_,i)=>arr.slice(i*size,i*size+size));
export const flatten = arr => arr.flat(Infinity);
export const compact = arr => arr.filter(Boolean);
export const zip = (...arrs) => arrs[0].map((_,i)=>arrs.map(a=>a[i]));
export const unzip = arr => arr[0].map((_,i)=>arr.map(a=>a[i]));
export const range = (start,end,step=1)=>Array.from({length:Math.floor((end-start)/step)+1},(_,i)=>start+i*step);
export const repeat = (value,count)=>Array(count).fill(value);
export const rotate = (arr,n=1)=>arr.slice(n).concat(arr.slice(0,n));
export const shuffle = arr=>[...arr].sort(()=>Math.random()-.5);
export const randomItem = arr=>arr[Math.floor(Math.random()*arr.length)];
export const randomItems=(arr,n)=>shuffle(arr).slice(0,n);
export const last = arr=>arr.at(-1);
export const first = arr=>arr[0];
export const difference=(a,b)=>(b=new Set(b),a.filter(x=>!b.has(x)));
export const union=(...arr)=>[...new Set(arr.flat())];
export const xor=(a,b)=>(b=new Set(b),[...a.filter(x=>!b.has(x)),...b].filter(x=>!new Set(a).has(x)));
export const sum=arr=>arr.reduce((a,b)=>a+b,0);
export const average=arr=>sum(arr)/arr.length;
export const maxBy=(arr,key)=>arr.reduce((a,b)=>a[key]>b[key]?a:b);
export const minBy=(arr,key)=>arr.reduce((a,b)=>a[key]<b[key]?a:b);
export const binarySearch=(arr,v)=>{let l=0,r=arr.length-1;while(l<=r){let m=(l+r)>>1;if(arr[m]===v)return m;arr[m]<v?l=m+1:r=m-1}return-1;}
export const insertAt=(arr,i,v)=>[...arr.slice(0,i),v,...arr.slice(i)];
export const removeAt=(arr,i)=>arr.filter((_,x)=>x!==i);
export const move=(arr,f,t)=>(arr=[...arr],arr.splice(t,0,arr.splice(f,1)[0]),arr);
